name: CI
on:
  push:
    branches:
      - master

jobs:
  node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: npm install and npm run build
        working-directory: ./ui
        run: |
          npm ci
          npm run build

  golang:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.13']
    steps:
      - uses: actions/checkout@v2
      - name: Go ${{ matrix.go }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - run: |
          go get github.com/rakyll/statik
          statik -src=ui/dist/ui
          go build -o kpack-viz main.go